Question: 1.
Given the following jumbled word, OBANWRI guess the correct English word.

A. RANIBOW
B. RAINBOW
C. BOWRANI
D. ROBWANI

In [ ]:
RAINBOW

Question 2:
Write a program that prints “LETS UPGRADE”. (Please note that you have to print in ALL CAPS
as given)

In [2]:
a = 'LETS upgrade'
print('"{}"'.format(a).upper())

"LETS UPGRADE"


Question 3:
Write a program that takes cost price and selling price as input and
displays whether the transaction is a Profit or a Loss or Neither.
INPUT FORMAT
● The first line contains the cost price.
● The second line contains the selling price.
OUTPUT FORMAT
● Print "Profit" if the transaction is a profit or "Loss" if it is a loss. If it is neither
● profit nor loss, print "Neither". (You must not have quotes in your output)

In [3]:
def pl(CP,SP):
    sum1 = (CP-SP)   
    if sum1 < 0:
        print('Profit')
    elif sum1 > 0:
        print('Loss')
    elif sum1 == 0:
        print('Neither')

In [4]:
#Test case:1
pl(20,30)
#Test case:2
pl(20,10)
#Test case:3
pl(20,20)
#Test case:4
pl(19,19)
#Test case:5
pl(23,7)
#Test case:6
pl(19,95)

Profit
Loss
Neither
Neither
Loss
Profit


Question 4:
Write a program that takes an amount in Euros as input. You need to find its equivalent in
Rupees and display it. Assume 1 Euro equals Rs. 80.
Please note that you are expected to stick to the given input and output
format as in sample test cases. Please don't add any extra lines such as
'Enter a number’ etc.
Your program should take only one number as input and display the output

In [5]:
def converter():
    Case = input(str('Case no: ',))
    Input = int(input('Input Euros: '))
    Output = print(Input * 88.28)

In [6]:
converter()

Case no: TEST CASE 1
Input Euros: 500
44140.0


Question 5:
Create an empty list. Accept 10 numbers from the user and append to it the list if it is an even
number.

In [7]:
# accept nested list from user
lis = []
list_size = int(input("Enter the number of list size "))

print("\n")

final_list = [int(input("Enter single number and press enter: ")) for _ in range(list_size)]
print("List is", final_list)

for i in final_list:
    if i%2==0:
        lis.append(i)
    else:
        pass
print('Appended list is',lis)


Enter the number of list size 10


Enter single number and press enter: 41
Enter single number and press enter: 78
Enter single number and press enter: 96
Enter single number and press enter: 35
Enter single number and press enter: 42
Enter single number and press enter: 24
Enter single number and press enter: 23
Enter single number and press enter: 59
Enter single number and press enter: 60
Enter single number and press enter: 71
List is [41, 78, 96, 35, 42, 24, 23, 59, 60, 71]
Appended list is [78, 96, 42, 24, 60]


Question 6:
Create a notebook on LIST COMPREHENSION. This exercise is to put you in a
Self-learning mode

List comprehensions provide us with a simple way to create a list based on some iterable. During the creation, elements from the iterable can be conditionally included in the new list and transformed as needed.
The list comprehensions are more efficient both computationally and in terms of coding space and time than a for loop. Typically, they are written in a single line of code.
n Python, we have also dictionary comprehensions and set comprehensions. All the principles we saw are the same for these comprehensions, too. We just have to know some very little details to create a dictionary or set comprehensions.
Dictionary Comprehensions:
To create a dictionary comprehension we just need to change the brackets [] to curly braces {}. Additionally, in the output expression, we need to separate key and value by a colon :.
To create a set comprehension we only need to change the brackets [] to curly braces {}.

List comprehensions provide us with a simple way to create a list based on some iterable.
The comprehensions are more efficient than using a for a loop.
We can use conditional statements in the comprehensions.
Comprehensions are a good alternative to the built-in map and filter functions.
We can have nested comprehensions.
In Python, we have also dictionary comprehensions and set comprehensions.
Generator expressions are preferable when we work with an infinite stream of a very large amount of data.


Question 7:
You have seen in the videos how powerful dictionary data structure is.
In this assignment, given a number n, you have to write a program that generates a dictionary
d which contains (i, i*i), where i is from 1 to n (both included).
Then you have to just print this dictionary d.

In [8]:
n=int(input("Input a number "))
d = dict()

for x in range(1,n+1):
    d[x]=x*x

print(d)

Input a number 8
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


Question 8
There is a robot that wants to go to the charging point to charge itself.
The robot moves in a 2-D plane from the original point (0,0). The robot can
move toward UP, DOWN, LEFT, and RIGHT with given steps.
The trace of robot movement is shown as the following:
UP 5
DOWN 3
LEFT 3
RIGHT 2
Then, the output of the program should be: 2
The numbers after the direction are steps.
Write a program to compute the distance between the current position after
a sequence of movement and the original point. If the distance is float, then
just print the nearest integer (use round() function for that and then convert
it into an integer).
Input Format:
The first line of the input contains a number n which implies the number of
directions to be given.
The next n lines contain the direction and the step separated by a space.
Output Format:
Print the distance from the original position to the current position.
Example:
Input: 4
UP 5
DOWN 3
LEFT 3
RIGHT 2
Output: 2

In [2]:
import math

In [3]:

position = [0,0]

moves = []

s = int(input('no of directions ',))


for i in range(s):
    moves=list(input('UP,DOWN,LEFT,RIGHT: ').split())
    direction = moves[0].upper()
    steps = int(moves[1])
    if direction=="UP":

        position[0] += steps

    elif direction=="DOWN":

        position[0] -= steps

    elif direction=="LEFT":

        position[1] -= steps

    elif direction=="RIGHT":

        position[1] += steps

    
    else:

        pass
print(round(math.sqrt(position[0]**2+position[1]**2)))

no of directions 4
UP,DOWN,LEFT,RIGHT: UP 5
UP,DOWN,LEFT,RIGHT: DOWN 3
UP,DOWN,LEFT,RIGHT: LEFT 3
UP,DOWN,LEFT,RIGHT: RIGHT 2
2


Questions 9:
Create a NumPy array starting from 2 till 50 with a step size of 3.

In [4]:
import numpy as np

In [5]:
a = np.arange(2,50,3)
a

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

Questions 10:
Accept two lists of 5 elements each from the user.
Convert them to NumPy arrays. Concatenate these arrays and print them. Also, sort these arrays
and print them.

In [6]:
number_list = []
n = int(input("Enter the list size "))

print("\n")
for i in range(0, n):
    item = int(input())
    number_list.append(item)
number_list1 = []
n = int(input("Enter the list size "))

print("\n")
for i in range(0, n):
    item = int(input())
    number_list1.append(item)
    
print(number_list)
print(number_list1)



Enter the list size 5


41
52
78
96
53
Enter the list size 5


14
25
36
58
68
[41, 52, 78, 96, 53]
[14, 25, 36, 58, 68]


In [7]:
#array
array1 = np.array(number_list)
array2 = np.array(number_list1)
print(array1)
print(array2)

[41 52 78 96 53]
[14 25 36 58 68]


In [8]:
#sort
sortarray1 = np.sort(array1)
sortarray2  =np.sort(array2)
print(sortarray1)
print(sortarray2)

[41 52 53 78 96]
[14 25 36 58 68]


In [9]:
#concatenate
arr = np.concatenate((sortarray1, sortarray2))
arr

array([41, 52, 53, 78, 96, 14, 25, 36, 58, 68])

In [12]:
arr.sort()
arr

array([14, 25, 36, 41, 52, 53, 58, 68, 78, 96])

Questions 11:
Write a code snippet to find the dimensions of a ndarray and its size.

In [13]:
ar =np.array([[7,8,4],
              [5,7,2]])
print('No of dimensions ',ar.ndim)
print('Shape of array ',ar.shape)

No of dimensions  2
Shape of array  (2, 3)


In [14]:
def shdim(ar):
    dim = ar.ndim
    shape = ar.shape
    print('No of dimensions ',dim)
    print('Shape of array ',shape)
shdim(ar)



No of dimensions  2
Shape of array  (2, 3)


Questions 12:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [15]:
arr4 = np.arange(4)
arr4.shape

# make it as row vector by inserting an axis along first dimension
row_vec = arr4[np.newaxis, :]     
row_vec.shape
#output(1, 4)

(1, 4)

In [16]:
# make it as column vector by inserting an axis along second dimension
col_vec = arr4[:, np.newaxis]  
col_vec.shape
#Out(4, 1)

(4, 1)

In [17]:
#array
arr5 =np.arange(5)
arr5

array([0, 1, 2, 3, 4])

In [18]:
#expand_Dims
np.expand_dims(arr5, axis=0)

array([[0, 1, 2, 3, 4]])

In [19]:
np.expand_dims(arr5, axis=1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

Questions 13:
Consider two square NumPy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()


In [20]:
arr6 = np.array([[4,2,8],
                [8,6,9],
                [1,4,7]])
arr7 = np.array([[9,6,3],
                [8,5,2],
                [7,4,1]])


In [21]:
np.vstack((arr6,arr7))

array([[4, 2, 8],
       [8, 6, 9],
       [1, 4, 7],
       [9, 6, 3],
       [8, 5, 2],
       [7, 4, 1]])

In [22]:
np.hstack((arr6,arr7))

array([[4, 2, 8, 9, 6, 3],
       [8, 6, 9, 8, 5, 2],
       [1, 4, 7, 7, 4, 1]])

Questions 14:
How to get unique items and counts of unique items?

In [ ]:
We can get unique items and their count by fuction  "value_counts"